### ISSUE TITLE
Update README with new syntax

### ISSUE THREAD

**Issue by udyux** [jonathantneal/postcss-short-data#3]
49215bd, as described in #2, brought a fundamental change to the syntax (replacing the `:` prefix for `-`) that hasn't been reflected in the README.

For example: `button[:target~="main"]` should now read `button[-target~="main"]`.

I couldn't figure out why my PostCSS wasn't getting modified at first.

**Comment by jonathantneal** [comment]
Thanks. This has been resolved by https://github.com/jonathantneal/postcss-short-data/pull/5
